project_id = "dkhrkignepqfidzdyper"

[functions."generate-card-logo"]
verify_jwt = true

[functions."send-family-invitation"]
verify_jwt = true

[functions."test-function"]
verify_jwt = false

[functions."hello"]
verify_jwt = false
