// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkhrkignepqfidzdyper.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRraHJraWduZXBxZmlkemR5cGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjQyMzEsImV4cCI6MjA2NDY0MDIzMX0.uAEA1hu87uLL4o833ikc7NKz9XLAL7XIKflpSFbBIPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);